export const FETCH_RANDOM_QUOTE_REQUEST = "FETCH_RANDOM_QUOTE_REQUEST";
export const FETCH_RANDOM_QUOTE_SUCCESS = "FETCH_RANDOM_QUOTE_SUCCESS";
export const FETCH_RANDOM_QUOTE_FAILURE = "FETCH_RANDOM_QUOTE_FAILURE";

export const FETCH_RANDOM_QUOTE_LIST_REQUEST =
  "FETCH_RANDOM_QUOTE_LIST_REQUEST";
export const FETCH_RANDOM_QUOTE_LIST_SUCCESS =
  "FETCH_RANDOM_QUOTE_LIST_SUCCESS";
export const FETCH_RANDOM_QUOTE_LIST_FAILURE =
  "FETCH_RANDOM_QUOTE_LIST_FAILURE";
